-- =============================================
-- Migration: הוספת תמיכה במבצעים (Promotions)
-- =============================================

-- טבלת מבצעים — מבצע per-store (אותו PromotionID יכול להופיע בכמה סניפים)
CREATE TABLE IF NOT EXISTS public.promotions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    promotion_id    TEXT NOT NULL,                    -- PromotionID מהXML
    description     TEXT DEFAULT '',                  -- PromotionDescription
    start_date      TIMESTAMP WITH TIME ZONE,        -- PromotionStartDateTime
    end_date        TIMESTAMP WITH TIME ZONE,        -- PromotionEndDateTime
    club_id         TEXT DEFAULT '0',                 -- ClubID: "0" = כולם, אחר = מועדון
    min_qty         INTEGER DEFAULT 1,               -- MinNoOfItemOffered
    allow_multiple  BOOLEAN DEFAULT false,            -- AllowMultipleDiscounts
    last_updated    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

    CONSTRAINT promotions_unique_store_promo UNIQUE (store_id, promotion_id)
);

CREATE INDEX IF NOT EXISTS idx_promotions_store ON promotions(store_id);
CREATE INDEX IF NOT EXISTS idx_promotions_end_date ON promotions(end_date);

-- טבלת פריטים במבצע — קישור בין promotion לפריטים
CREATE TABLE IF NOT EXISTS public.promotion_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id        BIGINT NOT NULL REFERENCES public.promotions(id) ON DELETE CASCADE,
    item_id             BIGINT NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
    group_id            TEXT DEFAULT '1',             -- GroupID מהXML
    reward_type         TEXT DEFAULT '1',             -- RewardType (1=הנחה, 2=מתנה)
    min_qty             REAL DEFAULT 0,               -- MinQty לרכישה
    discount_rate       REAL DEFAULT 0,               -- סכום ההנחה בש"ח
    discounted_price    REAL DEFAULT 0,               -- מחיר לאחר הנחה
    is_weighted         BOOLEAN DEFAULT false,        -- bIsWeighted

    CONSTRAINT promo_items_unique UNIQUE (promotion_id, item_id, group_id)
);

CREATE INDEX IF NOT EXISTS idx_promo_items_promotion ON promotion_items(promotion_id);
CREATE INDEX IF NOT EXISTS idx_promo_items_item ON promotion_items(item_id);

-- View: מבצעים פעילים — לשימוש באפליקציה
CREATE OR REPLACE VIEW active_promotions AS
SELECT
    pi.item_id,
    i.barcode,
    i.name AS item_name,
    p.promotion_id,
    p.description AS promo_description,
    p.start_date,
    p.end_date,
    p.club_id,
    pi.min_qty,
    pi.discount_rate,
    pi.discounted_price,
    s.branch_name,
    c.name AS chain_name,
    ct.name AS city_name
FROM promotion_items pi
JOIN promotions p ON pi.promotion_id = p.id
JOIN items i ON pi.item_id = i.id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
JOIN cities ct ON s.city_id = ct.id
WHERE p.end_date >= NOW()
  AND p.start_date <= NOW()
ORDER BY i.name, c.name;
