-- =============================================
-- 1. ניקוי והכנה (RESET)
-- =============================================

-- מחיקת ה-Views הקיימים כדי למנוע התנגשויות בעת שינוי הטבלאות
DROP VIEW IF EXISTS price_comparison;
DROP VIEW IF EXISTS cheapest_prices;

-- איפוס נתונים בטבלאות (משאיר את הטבלאות ריקות ונקיות)
TRUNCATE TABLE stores, prices, items RESTART IDENTITY CASCADE;


-- =============================================
-- 2. יצירת טבלאות תשתית חדשות
-- =============================================

-- טבלת ערים (לניהול אזורי סריקה)
CREATE TABLE IF NOT EXISTS public.cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,       -- שם העיר (למשל: פתח תקווה)
    is_active BOOLEAN DEFAULT true,  -- האם לסרוק עיר זו?
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- טבלת רשתות (לניהול הגדרות סקראפר לכל רשת)
CREATE TABLE IF NOT EXISTS public.chains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,              -- שם הרשת (למשל: רמי לוי)
    chain_code TEXT NOT NULL UNIQUE, -- קוד רשת רשמי
    scraper_type TEXT NOT NULL,      -- סוג מערכת: cerberus, binapro, etc.
    username TEXT,                   -- שם משתמש לפורטל
    base_url TEXT NOT NULL,          -- כתובת הפורטל
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =============================================
-- 3. עדכון טבלת החנויות (Stores)
-- =============================================

-- הוספת עמודות מקשרות (Foreign Keys) ושדות מזהים
ALTER TABLE public.stores 
ADD COLUMN IF NOT EXISTS chain_id BIGINT REFERENCES public.chains(id),
ADD COLUMN IF NOT EXISTS city_id BIGINT REFERENCES public.cities(id),
ADD COLUMN IF NOT EXISTS sub_chain_id TEXT, -- תת-רשת (למשל 001)
ADD COLUMN IF NOT EXISTS store_id TEXT,     -- מזהה החנות בקובץ (למשל 071)
ADD COLUMN IF NOT EXISTS raw_city_name TEXT; -- שם העיר כפי שמופיע במקור (לגיבוי)

-- מחיקת עמודת שם הרשת הישנה (כי עכשיו לוקחים את השם מטבלת chains)
-- אנחנו משאירים את branch_name!
ALTER TABLE public.stores DROP COLUMN IF EXISTS chain_name;

-- יצירת אינדקס לחיפוש מהיר של סניפים לפי רשת ועיר
CREATE INDEX IF NOT EXISTS idx_stores_lookup ON stores(chain_id, city_id);


-- =============================================
-- 4. יצירת ה-Views מחדש (מותאמים למבנה החדש)
-- =============================================

-- View: השוואת מחירים (כולל שם הרשת מטבלת chains)
CREATE OR REPLACE VIEW price_comparison AS
SELECT 
  i.id AS item_id,
  i.barcode,
  i.name,
  i.unit_measure,
  c.name as chain_name,  -- לוקח את השם מטבלת chains
  s.branch_name,         -- לוקח את שם הסניף מטבלת stores
  p.price,
  p.last_updated
FROM items i
JOIN prices p ON i.id = p.item_id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
ORDER BY i.name, c.name;

-- View: המחיר הזול ביותר
CREATE OR REPLACE VIEW cheapest_prices AS
SELECT 
  i.id AS item_id,
  i.barcode,
  i.name,
  i.unit_measure,
  MIN(p.price) AS cheapest_price,
  c.name AS cheapest_store, -- לוקח את השם מטבלת chains
  p.last_updated
FROM items i
JOIN prices p ON i.id = p.item_id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
GROUP BY i.id, i.barcode, i.name, i.unit_measure, c.name, p.last_updated;


-- =============================================
-- 5. הזנת נתונים ראשוניים (Seed Data)
-- =============================================

-- יצירת העיר פתח תקווה
INSERT INTO public.cities (name, is_active) 
VALUES ('פתח תקווה', true) 
ON CONFLICT (name) DO NOTHING;

-- יצירת רשת רמי לוי
INSERT INTO public.chains (name, chain_code, scraper_type, username, base_url)
VALUES ('רמי לוי', '7290027600007', 'cerberus', 'RamiLevi', 'https://url.retail.publishedprices.co.il/login')
ON CONFLICT (chain_code) DO NOTHING;
-- =============================================
-- 6. SEED DATA - נתוני בסיס (רשתות וערים)
-- =============================================

-- ערים (כולל עיר וירטואלית לאתרי אונליין)
INSERT INTO public.cities (name, is_active) VALUES 
('פתח תקווה', true),
('Internet', true)
ON CONFLICT (name) DO NOTHING;

-- רשתות (קבוצת Cerberus ושופרסל)
INSERT INTO public.chains (name, chain_code, scraper_type, username, base_url)
VALUES 
    ('רמי לוי', '7290027600007', 'cerberus', 'RamiLevi', 'https://url.retail.publishedprices.co.il/login'),
    ('אושר עד', '7290103152017', 'cerberus', 'OsherAd', 'http://url.retail.publishedprices.co.il/login'),
    ('ויקטורי', '7290696200003', 'laibcatalog', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('חצי חינם', '7290633800006', 'hazi-hinam', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('יוחננוף', '7290803800003', 'cerberus', 'Yohananof', 'http://url.retail.publishedprices.co.il/login'),
    ('מחסני השוק', '7290661400001', 'laibcatalog', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('קרפור / יינות ביתן', '7290027600007-BITAN', 'carrefour', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('שופרסל', '7290027600007-SHUF', 'shufersal', NULL, 'http://prices.shufersal.co.il/')
ON CONFLICT (chain_code) DO NOTHING;
-- יצירת אילוץ ייחודיות: שילוב של מזהה רשת + מזהה חנות חייב להיות חד-פעמי
ALTER TABLE public.stores 
ADD CONSTRAINT stores_unique_chain_store UNIQUE (chain_id, store_id);