-- =============================================
-- 1. ניקוי והכנה (RESET)
-- =============================================

-- מחיקת ה-Views הקיימים כדי למנוע התנגשויות בעת שינוי הטבלאות
DROP VIEW IF EXISTS price_comparison;
DROP VIEW IF EXISTS cheapest_prices;

-- איפוס נתונים בטבלאות (משאיר את הטבלאות ריקות ונקיות)
TRUNCATE TABLE stores, prices, items RESTART IDENTITY CASCADE;


-- =============================================
-- 2. יצירת טבלאות תשתית חדשות
-- =============================================

-- טבלת ערים (לניהול אזורי סריקה)
CREATE TABLE IF NOT EXISTS public.cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,       -- שם העיר (למשל: פתח תקווה)
    cbs_code TEXT UNIQUE,            -- קוד למ"ס (למשל: 7900 = פתח תקווה). NULL לעיר וירטואלית (Internet)
    is_active BOOLEAN DEFAULT true,  -- האם לסרוק עיר זו?
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- טבלת רשתות (לניהול הגדרות סקראפר לכל רשת)
CREATE TABLE IF NOT EXISTS public.chains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,              -- שם הרשת (למשל: רמי לוי)
    chain_code TEXT NOT NULL UNIQUE, -- קוד רשת רשמי
    scraper_type TEXT NOT NULL,      -- סוג מערכת: cerberus, binapro, etc.
    username TEXT,                   -- שם משתמש לפורטל
    base_url TEXT NOT NULL,          -- כתובת הפורטל
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =============================================
-- 3. עדכון טבלת החנויות (Stores)
-- =============================================

-- הוספת עמודות מקשרות (Foreign Keys) ושדות מזהים
ALTER TABLE public.stores 
ADD COLUMN IF NOT EXISTS chain_id BIGINT REFERENCES public.chains(id),
ADD COLUMN IF NOT EXISTS city_id BIGINT REFERENCES public.cities(id),
ADD COLUMN IF NOT EXISTS sub_chain_id TEXT, -- תת-רשת (למשל 001)
ADD COLUMN IF NOT EXISTS store_id TEXT,     -- מזהה החנות בקובץ (למשל 071)
ADD COLUMN IF NOT EXISTS raw_city_name TEXT; -- שם העיר כפי שמופיע במקור (לגיבוי)

-- מחיקת עמודות ישנות שהוחלפו ב-Foreign Keys
ALTER TABLE public.stores DROP COLUMN IF EXISTS chain_name; -- הוחלף ב-chain_id → chains.name
ALTER TABLE public.stores DROP COLUMN IF EXISTS city;       -- הוחלף ב-city_id → cities.name

-- יצירת אינדקס לחיפוש מהיר של סניפים לפי רשת ועיר
CREATE INDEX IF NOT EXISTS idx_stores_lookup ON stores(chain_id, city_id);

-- הוספת שם יצרן לטבלת פריטים
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS manufacturer_name TEXT DEFAULT '';


-- =============================================
-- 4. אבטחה: RLS + Policies
-- =============================================

-- הפעלת RLS על כל הטבלאות הציבוריות
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_items ENABLE ROW LEVEL SECURITY;

-- קריאה בלבד לכולם (הנתונים ציבוריים — חוק שקיפות מחירים)
-- כתיבה רק דרך service_role (הסקרייפר), שעוקף RLS אוטומטית
CREATE POLICY "Public read access" ON public.cities FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.chains FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.stores FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.items FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.prices FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.promotions FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.promotion_items FOR SELECT USING (true);

-- תיקון search_path לפונקציות trigger קיימות (מניעת SQL injection)
ALTER FUNCTION IF EXISTS public.update_modified_column() SET search_path = public;
ALTER FUNCTION IF EXISTS public.update_updated_at_column() SET search_path = public;


-- =============================================
-- 5. יצירת ה-Views מחדש (ללא SECURITY DEFINER)
-- =============================================

-- View: השוואת מחירים (כולל שם הרשת מטבלת chains)
DROP VIEW IF EXISTS price_comparison;
CREATE VIEW price_comparison WITH (security_invoker = true) AS
SELECT 
  i.id AS item_id,
  i.barcode,
  i.name,
  i.unit_measure,
  c.name as chain_name,  -- לוקח את השם מטבלת chains
  s.branch_name,         -- לוקח את שם הסניף מטבלת stores
  p.price,
  p.last_updated
FROM items i
JOIN prices p ON i.id = p.item_id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
ORDER BY i.name, c.name;

-- View: המחיר הזול ביותר
DROP VIEW IF EXISTS cheapest_prices;
CREATE VIEW cheapest_prices WITH (security_invoker = true) AS
SELECT 
  i.id AS item_id,
  i.barcode,
  i.name,
  i.unit_measure,
  MIN(p.price) AS cheapest_price,
  c.name AS cheapest_store, -- לוקח את השם מטבלת chains
  p.last_updated
FROM items i
JOIN prices p ON i.id = p.item_id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
GROUP BY i.id, i.barcode, i.name, i.unit_measure, c.name, p.last_updated;


-- =============================================
-- 6. טבלאות מבצעים (Promotions)
-- =============================================

-- טבלת מבצעים — מבצע per-store (אותו PromotionID יכול להופיע בכמה סניפים)
CREATE TABLE IF NOT EXISTS public.promotions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    promotion_id    TEXT NOT NULL,                    -- PromotionID מהXML
    description     TEXT DEFAULT '',                  -- PromotionDescription
    start_date      TIMESTAMP WITH TIME ZONE,        -- PromotionStartDateTime
    end_date        TIMESTAMP WITH TIME ZONE,        -- PromotionEndDateTime
    club_id         TEXT DEFAULT '0',                 -- ClubID: "0" = כולם, אחר = מועדון
    min_qty         INTEGER DEFAULT 1,               -- MinNoOfItemOffered
    allow_multiple  BOOLEAN DEFAULT false,            -- AllowMultipleDiscounts
    last_updated    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

    CONSTRAINT promotions_unique_store_promo UNIQUE (store_id, promotion_id)
);

CREATE INDEX IF NOT EXISTS idx_promotions_store ON promotions(store_id);
CREATE INDEX IF NOT EXISTS idx_promotions_end_date ON promotions(end_date);

-- טבלת פריטים במבצע — קישור בין promotion לפריטים
CREATE TABLE IF NOT EXISTS public.promotion_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id        BIGINT NOT NULL REFERENCES public.promotions(id) ON DELETE CASCADE,
    item_id             BIGINT NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
    group_id            TEXT DEFAULT '1',             -- GroupID מהXML
    reward_type         TEXT DEFAULT '1',             -- RewardType (1=הנחה, 2=מתנה)
    min_qty             REAL DEFAULT 0,               -- MinQty לרכישה
    discount_rate       REAL DEFAULT 0,               -- סכום ההנחה בש"ח
    discounted_price    REAL DEFAULT 0,               -- מחיר לאחר הנחה
    is_weighted         BOOLEAN DEFAULT false,        -- bIsWeighted

    CONSTRAINT promo_items_unique UNIQUE (promotion_id, item_id, group_id)
);

CREATE INDEX IF NOT EXISTS idx_promo_items_promotion ON promotion_items(promotion_id);
CREATE INDEX IF NOT EXISTS idx_promo_items_item ON promotion_items(item_id);

-- View: מבצעים פעילים — לשימוש באפליקציה
DROP VIEW IF EXISTS active_promotions;
CREATE VIEW active_promotions WITH (security_invoker = true) AS
SELECT
    pi.item_id,
    i.barcode,
    i.name AS item_name,
    p.promotion_id,
    p.description AS promo_description,
    p.start_date,
    p.end_date,
    p.club_id,
    pi.min_qty,
    pi.discount_rate,
    pi.discounted_price,
    s.branch_name,
    c.name AS chain_name,
    ct.name AS city_name
FROM promotion_items pi
JOIN promotions p ON pi.promotion_id = p.id
JOIN items i ON pi.item_id = i.id
JOIN stores s ON p.store_id = s.id
JOIN chains c ON s.chain_id = c.id
JOIN cities ct ON s.city_id = ct.id
WHERE p.end_date >= NOW()
  AND p.start_date <= NOW()
ORDER BY i.name, c.name;


-- =============================================
-- 7. הזנת נתונים ראשוניים (Seed Data)
-- =============================================

-- ערים (109 ערים כולל עיר וירטואלית לאתרי אונליין)
-- קוד למ"ס (cbs_code) משמש לזיהוי ערים מתוך XML של Cerberus ושופרסל
INSERT INTO public.cities (name, cbs_code, is_active) VALUES
    ('פתח תקווה',           '7900', true),
    ('Internet',             NULL,   true),
    ('ירושלים',              '3000', false),
    ('תל אביב - יפו',       '5000', false),
    ('חיפה',                 '4000', false),
    ('באר שבע',              '9000', false),
    ('ראשון לציון',          '8300', false),
    ('בני ברק',              '6100', false),
    ('רמת גן',              '8600', false),
    ('כפר סבא',              '6900', false),
    ('נתניה',                '7400', false),
    ('אשדוד',                '70',   false),
    ('אשקלון',               '7100', false),
    ('חדרה',                 '6500', false),
    ('בית שמש',              '2610', false),
    ('חולון',                '6600', false),
    ('בת ים',                '6200', false),
    ('רעננה',                '8700', false),
    ('רחובות',               '8400', false),
    ('קריית גת',             '2630', false),
    ('קריית ביאליק',         '9500', false),
    ('קריית אונו',           '2620', false),
    ('קריית שמונה',          '2800', false),
    ('הוד השרון',            '9700', false),
    ('הרצליה',               '6400', false),
    ('לוד',                  '7000', false),
    ('עכו',                  '7600', false),
    ('עפולה',                '7700', false),
    ('טבריה',                '6700', false),
    ('נשר',                  '2500', false),
    ('מודיעין-מכבים-רעות',   '1200', false),
    ('רמלה',                 '8500', false),
    ('נהריה',                '9100', false),
    ('אילת',                 '2600', false),
    ('ראש העין',             '2640', false),
    ('אור יהודה',            '2400', false),
    ('מגדל העמק',            '874',  false),
    ('כנות (אזור תעשייה)',   '2006', false),
    ('ביתר עילית',           '3780', false),
    ('אופקים',               '31',   false),
    ('פרדסיה',               '171',  false),
    ('קדימה צורן',           '195',  false),
    ('נתיבות',               '246',  false),
    ('גבעת שמואל',           '681',  false),
    ('באר יעקב',             '1034', false),
    ('מבשרת ציון',           '1015', false),
    ('שדרות',                '1031', false),
    ('כרמיאל',               '1139', false),
    ('מודיעין עילית',        '1165', false),
    ('יבנה',                 '2660', false),
    ('אריאל',                '3570', false),
    ('מעלה אדומים',          '3616', false),
    ('גבעתיים',              '6300', false),
    ('פרדס חנה-כרכור',       '7800', false),
    ('זכרון יעקב',           '9300', false),
    ('קריית ים',             '9600', false),
    -- ערים נוספות (שופרסל)
    ('אור עקיבא',            '1020', false),
    ('אלעד',                 '1309', false),
    ('אלקנה',                '3560', false),
    ('באר טוביה',             '155',  false),
    ('בארות יצחק',            '450',  false),
    ('בני דרור',              '386',  false),
    ('בנימינה',               '9800', false),
    ('בת חפר',                '1319', false),
    ('גבעת עדה',              '50',   false),
    ('גדרה',                  '2550', false),
    ('דימונה',                '2200', false),
    ('דלית אל כרמל',          '494',  false),
    ('חצור הגלילית',          '2034', false),
    ('חריש',                  '1247', false),
    ('טייבה',                 '2730', false),
    ('טירה',                  '2720', false),
    ('טירת הכרמל',            '2100', false),
    ('יהוד-מונוסון',          '9400', false),
    ('יוקנעם עילית',          '240',  false),
    ('ירוחם',                 '831',  false),
    ('ירכא',                  '502',  false),
    ('כפר יונה',              '168',  false),
    ('כפר נטר',               '316',  false),
    ('כפר ורדים',             '1263', false),
    ('כפר קרע',               '654',  false),
    ('כפר תבור',              '47',   false),
    ('מזכרת בתיה',            '28',   false),
    ('מיתר',                  '1268', false),
    ('מעלות-תרשיחא',          '1063', false),
    ('מצפה רמון',             '99',   false),
    ('משמר השרון',             '194',  false),
    ('נוף הגליל',             '1061', false),
    ('נס ציונה',              '7200', false),
    ('נצרת',                  '7300', false),
    ('סביון',                 '587',  false),
    ('סכנין',                 '7500', false),
    ('ערד',                   '2560', false),
    ('עומר',                  '666',  false),
    ('צור יגאל',              '1306', false),
    ('צור משה',               '276',  false),
    ('צורן',                  '1308', false),
    ('צפת',                   '8000', false),
    ('קצרין',                 '4100', false),
    ('קריית אתא',             '6800', false),
    ('קריית טבעון',           '2300', false),
    ('קריית מוצקין',          '8200', false),
    ('ראש פינה',              '26',   false),
    ('רהט',                   '1161', false),
    ('רכסים',                 '922',  false),
    ('רמת השרון',             '2650', false),
    ('שוהם',                  '1304', false),
    ('שפרעם',                 '8800', false),
    ('תל מונד',               '154',  false),
    ('עין שמר',               '139',  false),
    ('בית חשמונאי',           '1050', false),
    ('אפרת',                  '3650', false),
    ('בית שאן',               '9200', false),
    ('קריית עקרון',           '469',  false),
    ('קריית שדה התעופה',      '1746', false),
    ('אשדות יעקב (איחוד)',   '199',  false),
    ('גבע בנימין',            '3763', false),
    ('אלון שבות',             '3604', false)
ON CONFLICT (name) DO UPDATE SET cbs_code = EXCLUDED.cbs_code;

-- רשתות (קבוצת Cerberus ושופרסל)
INSERT INTO public.chains (name, chain_code, scraper_type, username, base_url)
VALUES 
    ('רמי לוי', '7290027600007', 'cerberus', 'RamiLevi', 'https://url.retail.publishedprices.co.il/login'),
    ('אושר עד', '7290103152017', 'cerberus', 'OsherAd', 'http://url.retail.publishedprices.co.il/login'),
    ('ויקטורי', '7290696200003', 'laibcatalog', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('חצי חינם', '7290633800006', 'hazi-hinam', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('יוחננוף', '7290803800003', 'cerberus', 'Yohananof', 'http://url.retail.publishedprices.co.il/login'),
    ('מחסני השוק', '7290661400001', 'laibcatalog', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('קרפור / יינות ביתן', '7290027600007-BITAN', 'carrefour', NULL, 'http://url.retail.publishedprices.co.il/login'),
    ('שופרסל', '7290027600007-SHUF', 'shufersal', NULL, 'http://prices.shufersal.co.il/')
ON CONFLICT (chain_code) DO NOTHING;
-- יצירת אילוץ ייחודיות: שילוב של מזהה רשת + מזהה חנות חייב להיות חד-פעמי
ALTER TABLE public.stores 
ADD CONSTRAINT stores_unique_chain_store UNIQUE (chain_id, store_id);